
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
#    url: jdbc:sqlserver://go-project.database.windows.net:1433;database=go-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net
#    username: projeto-go
#    password: #pedro_gracinha_123
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

#  spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=projeto-go
#spring.datasource.password=#pedro_gracinha_123
#spring.datasource.url=jdbc:sqlserver://go-project.database.windows.net:1433;database=go-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
